"""empty message

Revision ID: 584abb4a710f
Revises: 882507006d25
Create Date: 2019-09-04 10:55:47.901901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584abb4a710f'
down_revision = '882507006d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reparacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reparacion', sa.Column('detencion', sa.INTEGER(), nullable=True))
    op.add_column('reparacion', sa.Column('detencion_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
