"""empty message

Revision ID: 5ba1d7ae3a89
Revises: 584abb4a710f
Create Date: 2019-09-04 12:12:20.887370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba1d7ae3a89'
down_revision = '584abb4a710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reparacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('detencion_id', sa.Integer(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modify', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detencion_id'], ['detencion.id'], ),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reparacion')
    op.drop_table('detencion')
    # ### end Alembic commands ###
