"""empty message

Revision ID: 882507006d25
Revises: 4218e9ab1a18
Create Date: 2019-09-02 17:09:14.994158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882507006d25'
down_revision = '4218e9ab1a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reparacion', sa.Column('detencion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reparacion', 'detencion')
    # ### end Alembic commands ###
